version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:26.7.0
    steps:
      - checkout
      - run:
          name: Run Testim tests locally
          no_output_timeout: 30m
          command: |
            npx --yes @testim/testim-cli \
              --token "$TESTIM_TOKEN" \
              --project "$TESTIM_PROJECT_ID" \
              --base-url "https://vercel.app" \
              --grid "$TESTIM_GRID"
              --branch "master"
              --report-file $CIRCLE_TEST_REPORTS/testim/results.xml

workflows:
  version: 2
  test:
    jobs:
      - test